# Generated by Django 5.0.2 on 2024-03-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('year_released', models.IntegerField(blank=True, verbose_name='year released')),
                ('number_of_songs', models.IntegerField(blank=True, verbose_name='number of songs')),
                ('album_rating', models.IntegerField(blank=True, verbose_name='album rating')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('length', models.TimeField(blank=True, verbose_name='length')),
                ('bitrate', models.IntegerField(blank=True, verbose_name='bitrate')),
                ('year_released', models.IntegerField(blank=True, verbose_name='year released')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='genre')),
                ('track_rating', models.IntegerField(blank=True, verbose_name='track rating')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='audio')),
                ('audio_img', models.ImageField(blank=True, null=True, upload_to='audio_img/', verbose_name='audio picture')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
                'ordering': ['name'],
            },
        ),
    ]
